# Generated by Django 3.2.8 on 2021-10-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speed', models.FloatField(default=40, max_length=3)),
                ('avg_speed', models.FloatField(default=40, max_length=3)),
                ('temperature', models.FloatField(default=40, max_length=3)),
                ('fuel_level', models.IntegerField(default=60)),
                ('engine_status', models.CharField(default='OK', max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('ignition', models.BooleanField(default=False)),
                ('logo', models.ImageField(default='', upload_to='base/logo')),
                ('camera1', models.ImageField(default='', upload_to='base/camera1')),
                ('camera2', models.ImageField(default='', upload_to='base/camera2')),
                ('static_map', models.ImageField(default='', upload_to='base/static_map')),
            ],
        ),
    ]
